services:
  comfy-ui:
    build:
      context: ../Dockerfile
      dockerfile: Dockerfile
    image: comfy-ui:v0.19.0
    container_name: comfy-ui
    volumes:
      # --- Stable Diffusion系 ---
      - ../models/Illustrious/Checkpoint:/ComfyUI/models/checkpoints
      - ../models/Illustrious/LoRA:/ComfyUI/models/loras
      # --- Qwen Image系 ---
      # - ../models/Qwen-Image:/ComfyUI/models
      # --- wan2.2系 ---
      # - ../models/wan2.2/wan2.2_ti2v_5B:/ComfyUI/models
      # --- 出力 ---
      - ../output:/ComfyUI/output
    ports:
      - "8188:8188"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
